//! US-021 AC2 generative fuzz target for OWNER-DRIVER COMMAND/BYTE
//! SCHEDULES, at the ws-driver seam AC2 actually names.
//!
//! ## Why this file exists
//!
//! `assurance/fuzz/manifest.json` recorded this family `ABSENT`, and the
//! census was right on both counts:
//!
//! - `tests/schedule_exploration.rs` EXHAUSTIVELY ENUMERATES every
//!   interleaving of five fixed actor programs within a context-switch
//!   bound. That is systematic, deterministic and valuable, and it is not
//!   generative fuzzing: it draws nothing. Its alphabet is eleven fixed
//!   verbs and its inbound bytes are two fixed frames.
//! - `adversarial_fuzz.rs::family_command_interleave_no_panic_deterministic`
//!   DOES interleave generated commands with generated bytes, but against
//!   `ConnectionCore` — no `ConnectionDriver`, no owner poll loop, no
//!   transport write path. A different seam.
//!
//! This file draws schedules over a real [`ConnectionDriver`], drives the
//! owner poll loop, and models a transport that accepts write suffixes
//! incrementally. Zero new dependencies: the hand-rolled SplitMix64 from
//! fixed committed seeds is the engine, as in `adversarial_fuzz.rs`.
//!
//! ## What is generated that the enumeration does not draw
//!
//! - inbound BYTES: raw frames built independently of the shipped encoder
//!   (arbitrary FIN/RSV/opcode, both maskings, noncanonical length escapes,
//!   hostile close payloads, invalid UTF-8), plus byte soup and truncations;
//! - commands: all six `LocalCommand` kinds with drawn payloads, from two
//!   producers sharing the bounded `CommandSender`;
//! - write progress: zero, one, a drawn partial, the whole suffix, and
//!   DELIBERATELY OVER the suffix (which must be refused, not absorbed);
//! - both `AutoResponsePolicy` values and both `CloseEchoPolicy` values.
//!   The exploration suite runs `AutoResponsePolicy::Disabled` only and
//!   discloses that it therefore cannot reach any interaction between the
//!   automatic reply and shutdown; this campaign draws the default policy
//!   too.
//!
//! ## Oracles (checked on every case)
//!
//! - **No panic** — every run is under `catch_unwind`, failing the case
//!   with its seed label.
//! - **Determinism** — the same drawn schedule replays to a byte-identical
//!   trace.
//! - **Producer purity (single owner)** — a `CommandSender::try_send` must
//!   not move `driver.state()` or `driver.counts()`. Only the owner's poll
//!   may move a protocol observable.
//! - **Write-suffix continuity** — after the transport accepts `k` bytes of
//!   an offered suffix, the next offer must be exactly that suffix minus its
//!   first `k` bytes (or a different write once the front is fully drained).
//!   The driver may neither re-offer accepted bytes nor drop unaccepted
//!   ones.
//! - **Invalid write progress is refused and inert** — progress past the
//!   offered suffix must come back `Rejected(InvalidWriteProgress)` with the
//!   real `attempted`/`remaining`, and must move no observable at all.
//! - **Exactly-once terminal** — at most one `DriverOutput::Terminal` per
//!   run.
//! - **Shutdown accounting** — at most one `WritesDropped` report; it must
//!   precede any `Terminal`; `frames == 0` exactly when `bytes == 0`; and
//!   when the boundary was holding a partly drained front write, the report
//!   must account for at least its undrained suffix and must set
//!   `partial_front` exactly when the wire had already seen some of it.
//! - **Bounded output for a bounded schedule** — a drain loop of
//!   [`DRAIN_WORK_BOUND`] polls must reach quiescence. This is a WORK bound
//!   on a deterministic drain, not a liveness guard; the campaign's liveness
//!   guard is the wall-clock deadline in the manifest (finding F005).

#![forbid(unsafe_code)]

use std::panic::{AssertUnwindSafe, catch_unwind};

use ws_core::config::ConnectionConfig;
use ws_core::connection::DataOpcode;
use ws_core::{CommandSender, InitialState, LocalCommand, ReadyState, Role, SemanticEvent};
use ws_driver::{
    AutoResponsePolicy, CloseEchoPolicy, CommandDisposition, ConnectionDriver, DriverInput,
    DriverInputError, DriverOutput, DroppedWrites, InputDisposition,
    connection_driver_in_state_with_policies,
};

// ---------------------------------------------------------------------------
// Deterministic PRNG (SplitMix64) — fixed committed seeds only.
// ---------------------------------------------------------------------------

#[derive(Clone)]
struct SplitMix64 {
    state: u64,
}

impl SplitMix64 {
    fn new(seed: u64) -> SplitMix64 {
        SplitMix64 { state: seed }
    }

    fn next_u64(&mut self) -> u64 {
        self.state = self.state.wrapping_add(0x9e37_79b9_7f4a_7c15);
        let mut z = self.state;
        z = (z ^ (z >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
        z ^ (z >> 31)
    }

    fn below(&mut self, n: u64) -> u64 {
        assert!(n > 0);
        self.next_u64() % n
    }

    fn byte(&mut self) -> u8 {
        (self.next_u64() & 0xff) as u8
    }

    fn chance(&mut self, one_in: u64) -> bool {
        self.below(one_in) == 0
    }

    fn bytes(&mut self, len: usize) -> Vec<u8> {
        (0..len).map(|_| self.byte()).collect()
    }
}

/// Work bound for the quiescence drain. Exceeding it means a bounded
/// schedule produced unbounded owner output, which is the defect this
/// bound exists to catch. It is NOT the campaign's liveness guard: that is
/// the wall-clock deadline recorded in `assurance/fuzz/manifest.json`.
const DRAIN_WORK_BOUND: usize = 512;

// ---------------------------------------------------------------------------
// Independent frame construction (never calls the shipped encoder).
// ---------------------------------------------------------------------------

fn xor_mask(payload: &mut [u8], key: [u8; 4]) {
    for (index, byte) in payload.iter_mut().enumerate() {
        *byte ^= key[index % 4];
    }
}

fn raw_frame(
    fin: bool,
    rsv: u8,
    opcode: u8,
    payload: &[u8],
    mask: Option<[u8; 4]>,
    force_escape: Option<u8>,
) -> Vec<u8> {
    let mut out = Vec::with_capacity(payload.len() + 14);
    let mut first = opcode & 0x0f;
    if fin {
        first |= 0x80;
    }
    first |= (rsv & 0x07) << 4;
    out.push(first);
    let mask_bit = if mask.is_some() { 0x80u8 } else { 0 };
    let len = payload.len() as u64;
    let escape = match force_escape {
        Some(marker) => marker,
        None if len <= 125 => 0,
        None if len <= 0xffff => 126,
        None => 127,
    };
    match escape {
        126 => {
            out.push(mask_bit | 126);
            out.extend_from_slice(&(len as u16).to_be_bytes());
        }
        127 => {
            out.push(mask_bit | 127);
            out.extend_from_slice(&len.to_be_bytes());
        }
        _ => out.push(mask_bit | (len as u8)),
    }
    if let Some(key) = mask {
        out.extend_from_slice(&key);
        let start = out.len();
        out.extend_from_slice(payload);
        xor_mask(&mut out[start..], key);
    } else {
        out.extend_from_slice(payload);
    }
    out
}

fn draw_close_payload(rng: &mut SplitMix64, hostile: bool) -> Vec<u8> {
    if !hostile {
        let mut payload = 1000u16.to_be_bytes().to_vec();
        payload.extend((0..rng.below(12)).map(|_| (rng.byte() & 0x3f) + 0x20));
        return payload;
    }
    match rng.below(10) {
        0 => Vec::new(),
        1 => vec![rng.byte()],
        _ => {
            const CODES: [u16; 12] = [
                999, 1000, 1001, 1002, 1005, 1006, 1007, 1011, 1015, 2999, 4999, 5000,
            ];
            let code = if rng.chance(4) {
                (rng.next_u64() & 0xffff) as u16
            } else {
                CODES[rng.below(CODES.len() as u64) as usize]
            };
            let mut payload = code.to_be_bytes().to_vec();
            let reason_len = rng.below(20) as usize;
            payload.extend((0..reason_len).map(|_| rng.byte()));
            payload
        }
    }
}

/// One structured inbound frame.
///
/// ## The hostile/well-formed split, and why it exists
///
/// `role` is the LOCAL endpoint, so it decides the masking a peer frame must
/// carry: a server reads client frames, which must be masked, and a client
/// reads server frames, which must not be.
///
/// A generator that draws every field uniformly produces a frame that is
/// PROTOCOL-FATAL most of the time -- unmasked to a server, invalid UTF-8 in
/// a text frame, a reserved opcode, a non-FIN control frame, a continuation
/// with no open fragment. The modeled adapter halts at its first surfaced
/// fatal, exactly like the shipped ws-testee io_loop, so a uniform generator
/// kills its own runs before they reach the driver behavior this campaign
/// exists to exercise. Measured on the uniform version of this generator:
/// 3,470 of 4,000 cases surfaced a fatal and only 134 reached a terminal.
///
/// So three frames in four are drawn WELL-FORMED (role-correct masking, FIN
/// set, a real opcode, valid UTF-8 text, a valid close payload) and the
/// fourth is drawn hostile across every one of those axes. The coverage
/// floors asserted at the end of the campaign are what keep this split
/// honest.
fn draw_frame(rng: &mut SplitMix64, role: Role) -> Vec<u8> {
    let hostile = rng.chance(4);
    let opcode: u8 = if hostile {
        match rng.below(20) {
            0..=1 => 0x0,
            2..=5 => 0x1,
            6..=8 => 0x2,
            9..=12 => 0x8,
            13..=16 => 0x9,
            17..=18 => 0xa,
            _ => rng.byte() & 0x0f,
        }
    } else {
        const WELL_FORMED: [u8; 5] = [0x1, 0x2, 0x9, 0xa, 0x8];
        WELL_FORMED[rng.below(WELL_FORMED.len() as u64) as usize]
    };
    let control = opcode >= 0x8;
    let fin = if hostile { !rng.chance(3) } else { true };
    let rsv = if hostile && rng.chance(3) {
        1 << rng.below(3)
    } else {
        0
    };
    let len = if control {
        rng.below(126) as usize
    } else {
        rng.below(160) as usize
    };
    let payload = match opcode {
        0x8 => draw_close_payload(rng, hostile),
        // A text frame carrying random bytes is almost surely invalid UTF-8,
        // which is fatal. Well-formed text is printable ASCII.
        0x1 if !hostile => (0..len).map(|_| (rng.byte() & 0x3f) + 0x20).collect(),
        _ => rng.bytes(len),
    };
    let peer_masks = role == Role::Server;
    let masked = if hostile && rng.chance(3) {
        !peer_masks
    } else {
        peer_masks
    };
    let mask = if masked {
        Some([rng.byte(), rng.byte(), rng.byte(), rng.byte()])
    } else {
        None
    };
    let force_escape = if payload.len() <= 125 && hostile && rng.chance(8) {
        Some(if rng.chance(2) { 126 } else { 127 })
    } else {
        None
    };
    raw_frame(fin, rsv, opcode, &payload, mask, force_escape)
}

fn draw_command(rng: &mut SplitMix64) -> LocalCommand {
    match rng.below(6) {
        0 => LocalCommand::SendText {
            text: String::from_utf8(
                (0..rng.below(60))
                    .map(|_| (rng.byte() & 0x3f) + 0x20)
                    .collect::<Vec<u8>>(),
            )
            .expect("printable ascii"),
        },
        1 => {
            let len = rng.below(120) as usize;
            LocalCommand::SendBinary {
                data: rng.bytes(len),
            }
        }
        2 => {
            let len = rng.below(126) as usize;
            LocalCommand::SendPing {
                data: rng.bytes(len),
            }
        }
        3 => {
            let len = rng.below(126) as usize;
            LocalCommand::SendPong {
                data: rng.bytes(len),
            }
        }
        4 => {
            const CODES: [u16; 8] = [1000, 1001, 1002, 1005, 1007, 1015, 3000, 4999];
            LocalCommand::SendClose {
                code: if rng.chance(3) {
                    (rng.next_u64() & 0xffff) as u16
                } else {
                    CODES[rng.below(CODES.len() as u64) as usize]
                },
                reason: String::from_utf8(
                    (0..rng.below(20))
                        .map(|_| (rng.byte() & 0x3f) + 0x20)
                        .collect::<Vec<u8>>(),
                )
                .expect("printable ascii"),
            }
        }
        _ => LocalCommand::SendFragment {
            opcode: if rng.chance(2) {
                DataOpcode::Text
            } else {
                DataOpcode::Binary
            },
            data: (0..rng.below(40)).map(|_| rng.byte()).collect(),
            fin: rng.chance(2),
        },
    }
}

// ---------------------------------------------------------------------------
// The drawn schedule alphabet.
// ---------------------------------------------------------------------------

/// One schedule step. Unlike the eleven fixed verbs of the exhaustive
/// exploration, every payload here is DRAWN.
#[derive(Debug, Clone, PartialEq, Eq)]
enum Step {
    /// Producer A or B enqueues a drawn command through the shared bounded
    /// `CommandSender`.
    Enqueue {
        producer: u8,
        command: LocalCommand,
    },
    /// Drawn inbound transport bytes.
    Inbound(Vec<u8>),
    /// The transport accepted this many bytes of the offered suffix. Drawn
    /// values include zero, one, a partial, the whole suffix, and values
    /// PAST the suffix, which must be refused.
    WriteProgress(usize),
    TransportEof,
    Shutdown,
    Wake,
}

/// How a `WriteProgress` value is chosen relative to the offered suffix.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ProgressKind {
    None,
    One,
    Partial,
    Whole,
    /// Deliberately past the end: this must be refused, not absorbed.
    Overrun,
}

fn draw_progress_kind(rng: &mut SplitMix64) -> ProgressKind {
    match rng.below(10) {
        0 => ProgressKind::None,
        1..=2 => ProgressKind::One,
        3..=4 => ProgressKind::Partial,
        5..=7 => ProgressKind::Whole,
        _ => ProgressKind::Overrun,
    }
}

/// Draw one bounded schedule. `WriteProgress` carries a placeholder that the
/// run resolves against the suffix actually offered at that moment; the
/// KIND is what the schedule fixes, which keeps the schedule replayable.
fn draw_schedule(rng: &mut SplitMix64, role: Role) -> Vec<(Step, ProgressKind)> {
    let length = 1 + rng.below(24) as usize;
    (0..length)
        .map(|_| {
            let kind = draw_progress_kind(rng);
            let step = match rng.below(16) {
                0..=4 => Step::Enqueue {
                    producer: rng.byte() & 1,
                    command: draw_command(rng),
                },
                5..=8 => {
                    if rng.chance(6) {
                        let len = rng.below(40) as usize;
                        Step::Inbound(rng.bytes(len))
                    } else {
                        Step::Inbound(draw_frame(rng, role))
                    }
                }
                9..=11 => Step::WriteProgress(0),
                12 => Step::TransportEof,
                13 => Step::Shutdown,
                _ => Step::Wake,
            };
            (step, kind)
        })
        .collect()
}

// ---------------------------------------------------------------------------
// The modeled adapter boundary.
// ---------------------------------------------------------------------------

/// Everything the run observed, in order. Two runs of the same schedule must
/// produce equal traces (the determinism oracle).
#[derive(Debug, Clone, PartialEq, Eq)]
struct Trace {
    dispositions: Vec<CommandDisposition>,
    events: Vec<SemanticEvent>,
    /// Bytes the modeled transport accepted, concatenated in acceptance
    /// order.
    wire: Vec<u8>,
    /// Ordered output-kind tags, so a reordering shows up as a difference.
    outputs: Vec<&'static str>,
    input_dispositions: Vec<InputDisposition>,
    terminals: usize,
    failures: usize,
    dropped: Vec<DroppedWrites>,
    refused_enqueues: usize,
    final_state: ReadyState,
    halted: bool,
}

impl Trace {
    fn empty() -> Trace {
        Trace {
            dispositions: Vec::new(),
            events: Vec::new(),
            wire: Vec::new(),
            outputs: Vec::new(),
            input_dispositions: Vec::new(),
            terminals: 0,
            failures: 0,
            dropped: Vec::new(),
            refused_enqueues: 0,
            final_state: ReadyState::Open,
            halted: false,
        }
    }
}

/// One poll result, detached from the `&mut ConnectionDriver` borrow that
/// produced it. `PollResult<'owner>` holds the driver borrowed for as long
/// as it lives, so every oracle here works on this owned copy instead.
#[derive(Debug, Clone, PartialEq, Eq)]
struct OwnedPoll {
    input: InputDisposition,
    command: Option<CommandDisposition>,
    output: OwnedOutput,
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum OwnedOutput {
    Idle,
    Write(Vec<u8>),
    Event(SemanticEvent),
    Failure,
    WritesDropped(DroppedWrites),
    Terminal,
}

impl OwnedOutput {
    fn tag(&self) -> &'static str {
        match self {
            OwnedOutput::Idle => "idle",
            OwnedOutput::Write(_) => "write",
            OwnedOutput::Event(_) => "event",
            OwnedOutput::Failure => "failure",
            OwnedOutput::WritesDropped(_) => "writes_dropped",
            OwnedOutput::Terminal => "terminal",
        }
    }
}

struct Run {
    driver: ConnectionDriver,
    sender: CommandSender,
    trace: Trace,
    /// The write the transport is currently draining. `original` is the
    /// suffix as FIRST offered for this write; `accepted` is how much of it
    /// the wire has taken since. Tracking the original rather than the
    /// re-offered tail is what lets the boundary say whether the front write
    /// is PARTLY on the wire -- the driver re-offers only the undrained
    /// tail, so a boundary that forgot the original would answer "nothing
    /// accepted" for every write it had already started.
    front: Option<FrontWrite>,
    /// What the boundary was still owed when the adapter announced it could
    /// serve the transport no longer. `DriverInput::Shutdown` abandons
    /// pending writes, so `front` is cleared at that instant and this
    /// snapshot is what the dropped-write report is checked against.
    owed_snapshot: Option<FrontWrite>,
    /// Index into `trace.outputs` where a `WritesDropped` was seen.
    dropped_at: Option<usize>,
    /// Index where a `Terminal` was seen.
    terminal_at: Option<usize>,
    halted: bool,
}

/// One transport write the boundary is draining.
#[derive(Debug, Clone, PartialEq, Eq)]
struct FrontWrite {
    /// The suffix as first offered for this write.
    original: Vec<u8>,
    /// Bytes of `original` the modeled transport has accepted.
    accepted: usize,
}

impl FrontWrite {
    fn remaining(&self) -> usize {
        self.original.len() - self.accepted
    }

    fn tail(&self) -> &[u8] {
        &self.original[self.accepted..]
    }
}

fn config() -> ConnectionConfig {
    ConnectionConfig::builder()
        .event_queue_capacity(256)
        .write_queue_capacity(256)
        .command_queue_capacity(8)
        .build()
        .expect("driver fuzz config is valid")
}

impl Run {
    fn new(role: Role, auto: AutoResponsePolicy, echo: CloseEchoPolicy) -> Run {
        let (sender, driver) = connection_driver_in_state_with_policies(
            config(),
            role,
            InitialState::Open,
            auto,
            echo,
        );
        Run {
            driver,
            sender,
            trace: Trace::empty(),
            front: None,
            owed_snapshot: None,
            dropped_at: None,
            terminal_at: None,
            halted: false,
        }
    }

    /// One owner poll, detached from the driver borrow and folded into the
    /// trace with every ordering and continuity oracle applied.
    fn poll(&mut self, label: &str, input: DriverInput<'_>) {
        if self.halted {
            return;
        }
        let is_shutdown = matches!(input, DriverInput::Shutdown);
        let owned = self.poll_owned(input);
        if is_shutdown && matches!(owned.input, InputDisposition::Consumed { .. }) {
            // The adapter has announced it can serve the transport no
            // longer, so the offered write is no longer deliverable. Snapshot
            // what was owed for the accounting oracle, then stop treating it
            // as an offer.
            self.owed_snapshot = self.front.take();
        }
        self.absorb(label, owned);
    }

    /// Detach one poll result from the `&mut ConnectionDriver` borrow.
    fn poll_owned(&mut self, input: DriverInput<'_>) -> OwnedPoll {
        let result = self.driver.poll(input);
        OwnedPoll {
            input: result.input,
            command: result.command,
            output: match result.output {
                DriverOutput::Idle => OwnedOutput::Idle,
                DriverOutput::Write(suffix) => OwnedOutput::Write(suffix.to_vec()),
                DriverOutput::Event(event) => OwnedOutput::Event(event),
                DriverOutput::Failure { .. } => OwnedOutput::Failure,
                DriverOutput::WritesDropped(report) => OwnedOutput::WritesDropped(report),
                DriverOutput::Terminal(_) => OwnedOutput::Terminal,
            },
        }
    }

    /// Fold one owned poll result into the trace.
    fn absorb(&mut self, label: &str, owned: OwnedPoll) {
        self.trace.input_dispositions.push(owned.input);
        if let Some(disposition) = owned.command {
            self.trace.dispositions.push(disposition);
        }
        self.trace.outputs.push(owned.output.tag());
        match owned.output {
            OwnedOutput::Idle => {}
            OwnedOutput::Write(suffix) => {
                match &self.front {
                    // Write-suffix continuity: once the transport has taken
                    // some of a write, every later offer of it must be
                    // exactly the undrained tail -- the driver may neither
                    // re-offer accepted bytes nor drop unaccepted ones.
                    Some(front) if front.accepted > 0 => assert_eq!(
                        suffix.as_slice(),
                        front.tail(),
                        "{label}: the driver re-offered a suffix that is not the \
                         undrained tail of the write the transport was draining"
                    ),
                    // The same untouched write, offered again.
                    Some(front) if front.original == suffix => {}
                    // A different write takes the front.
                    _ => {
                        self.front = Some(FrontWrite {
                            original: suffix,
                            accepted: 0,
                        });
                    }
                }
            }
            OwnedOutput::Event(event) => self.trace.events.push(event),
            OwnedOutput::Failure => {
                self.trace.failures += 1;
                // The modeled adapter halts at its first surfaced fatal,
                // exactly like the shipped ws-testee io_loop.
                self.halted = true;
            }
            OwnedOutput::WritesDropped(report) => {
                assert!(
                    self.dropped_at.is_none(),
                    "{label}: a second WritesDropped report was surfaced"
                );
                self.dropped_at = Some(self.trace.outputs.len() - 1);
                self.assert_shutdown_accounting(label, report);
                self.trace.dropped.push(report);
            }
            OwnedOutput::Terminal => {
                assert!(
                    self.terminal_at.is_none(),
                    "{label}: the exactly-once terminal was delivered twice"
                );
                self.terminal_at = Some(self.trace.outputs.len() - 1);
                self.trace.terminals += 1;
            }
        }
    }

    /// US-017 AC2: committed writes an ended transport can no longer deliver
    /// are handed back, never silently abandoned. The boundary knows what it
    /// was holding, so it can check the report against it.
    fn assert_shutdown_accounting(&self, label: &str, report: DroppedWrites) {
        assert_eq!(
            report.frames == 0,
            report.bytes == 0,
            "{label}: a dropped-write report with {} frames carries {} bytes",
            report.frames,
            report.bytes
        );
        match &self.owed_snapshot {
            Some(front) if front.remaining() > 0 => {
                let undrained = front.remaining();
                assert!(
                    report.frames >= 1,
                    "{label}: the transport still owed {undrained} bytes of the front \
                     write and the report accounted for no frame at all"
                );
                assert!(
                    report.bytes >= undrained,
                    "{label}: the report accounts for {} bytes but the front write \
                     alone still owed {undrained}",
                    report.bytes
                );
                assert_eq!(
                    report.partial_front,
                    front.accepted > 0,
                    "{label}: partial_front disagrees with the wire ({} bytes of the \
                     front write had already been accepted)",
                    front.accepted
                );
            }
            _ => assert!(
                !report.partial_front,
                "{label}: partial_front is set but the boundary held no partly \
                 drained front write"
            ),
        }
    }

    /// Apply one resolved schedule step.
    fn exec(&mut self, label: &str, step: &Step, kind: ProgressKind, rng: &mut SplitMix64) {
        if self.halted {
            return;
        }
        match step {
            Step::Enqueue { command, .. } => {
                // Producer purity: enqueueing must move NO protocol
                // observable. Only the owner's poll may.
                let state_before = self.driver.state();
                let counts_before = self.driver.counts();
                if self.sender.try_send(command.clone()).is_err() {
                    self.trace.refused_enqueues += 1;
                }
                assert_eq!(
                    self.driver.state(),
                    state_before,
                    "{label}: a producer enqueue moved the lifecycle state"
                );
                assert_eq!(
                    self.driver.counts(),
                    counts_before,
                    "{label}: a producer enqueue moved a protocol counter"
                );
            }
            Step::Inbound(bytes) => self.poll(label, DriverInput::Inbound(bytes)),
            Step::WriteProgress(_) => self.write_progress(label, kind, rng),
            Step::TransportEof => self.poll(label, DriverInput::TransportEof),
            Step::Shutdown => self.poll(label, DriverInput::Shutdown),
            Step::Wake => self.poll(label, DriverInput::Wake),
        }
    }

    /// Resolve a `WriteProgress` step against the suffix offered right now.
    fn write_progress(&mut self, label: &str, kind: ProgressKind, rng: &mut SplitMix64) {
        let Some(front) = self.front.clone() else {
            // No write is offered: any nonzero progress must be refused.
            let bytes = match kind {
                ProgressKind::None => 0,
                _ => 1,
            };
            self.assert_progress_refused_or_zero(label, bytes, 0);
            return;
        };
        let remaining = front.remaining();
        let bytes = match kind {
            ProgressKind::None => 0,
            ProgressKind::One => 1.min(remaining),
            ProgressKind::Partial => {
                if remaining <= 1 {
                    remaining
                } else {
                    1 + rng.below(remaining as u64 - 1) as usize
                }
            }
            ProgressKind::Whole => remaining,
            ProgressKind::Overrun => remaining + 1 + rng.below(4) as usize,
        };
        if bytes > remaining {
            self.assert_progress_refused_or_zero(label, bytes, remaining);
            return;
        }
        let owned = self.poll_owned(DriverInput::WriteProgress { bytes });
        assert_eq!(
            owned.input,
            InputDisposition::Consumed { bytes: 0 },
            "{label}: in-range write progress of {bytes}/{remaining} was not consumed"
        );
        self.trace
            .wire
            .extend_from_slice(&front.original[front.accepted..front.accepted + bytes]);
        let accepted = front.accepted + bytes;
        self.front = if accepted == front.original.len() {
            None
        } else {
            Some(FrontWrite {
                original: front.original,
                accepted,
            })
        };
        self.absorb(label, owned);
    }

    /// Progress past the offered suffix (or with nothing offered) must be
    /// refused with the exact typed error, carrying the REAL `attempted` and
    /// `remaining`, and must put no byte on the wire.
    ///
    /// It may NOT additionally be asserted here that nothing else moved. A
    /// `ConnectionDriver::poll` is an owner TURN whatever its input carries:
    /// on the same call the owner may pop a queued producer command, apply
    /// it, and commit its frame, so `state()` and `counts()` legitimately
    /// advance on a poll whose INPUT was refused. Asserting otherwise is an
    /// oracle bug, and it was one here until the campaign caught it at
    /// schedule case 283. The property in its strong form -- a refusal on a
    /// QUIESCENT owner moves literally nothing -- is where it is actually
    /// true, in
    /// `owner_driver_invalid_write_progress_on_a_quiescent_owner_moves_nothing`.
    fn assert_progress_refused_or_zero(&mut self, label: &str, bytes: usize, remaining: usize) {
        let wire_before = self.trace.wire.len();
        let owned = self.poll_owned(DriverInput::WriteProgress { bytes });
        if bytes == 0 && remaining > 0 {
            // Zero progress on an offered write is legal and inert.
            assert_eq!(owned.input, InputDisposition::Consumed { bytes: 0 });
        } else {
            assert_eq!(
                owned.input,
                InputDisposition::Rejected(DriverInputError::InvalidWriteProgress {
                    attempted: bytes,
                    remaining,
                }),
                "{label}: write progress of {bytes} against {remaining} offered bytes \
                 was not refused with the typed error"
            );
            assert_eq!(
                self.trace.wire.len(),
                wire_before,
                "{label}: a refused write progress put bytes on the wire"
            );
        }
        self.absorb(label, owned);
    }

    /// Drain to quiescence within the work bound, accepting every offered
    /// write in full.
    fn drain(&mut self, label: &str) {
        for _ in 0..DRAIN_WORK_BOUND {
            if self.halted {
                return;
            }
            let before = self.trace.outputs.len();
            self.poll(label, DriverInput::Wake);
            if let Some(front) = self.front.clone()
                && front.remaining() > 0
            {
                let owned = self.poll_owned(DriverInput::WriteProgress {
                    bytes: front.remaining(),
                });
                assert_eq!(owned.input, InputDisposition::Consumed { bytes: 0 });
                self.trace.wire.extend_from_slice(front.tail());
                self.front = None;
                self.absorb(label, owned);
                continue;
            }
            if self.trace.outputs.len() == before + 1 && self.trace.outputs[before] == "idle" {
                return;
            }
        }
        panic!(
            "{label}: the owner produced output for {DRAIN_WORK_BOUND} consecutive polls \
             on a bounded schedule without reaching quiescence"
        );
    }

    fn finish(mut self, label: &str) -> Trace {
        self.drain(label);
        if let (Some(dropped), Some(terminal)) = (self.dropped_at, self.terminal_at) {
            assert!(
                dropped < terminal,
                "{label}: the dropped-write report was surfaced AFTER the terminal; \
                 US-017 AC2 orders it before"
            );
        }
        self.trace.final_state = self.driver.state();
        self.trace.halted = self.halted;
        self.trace
    }
}

/// Execute one drawn schedule end to end.
fn execute(
    label: &str,
    schedule: &[(Step, ProgressKind)],
    role: Role,
    auto: AutoResponsePolicy,
    echo: CloseEchoPolicy,
    progress_seed: u64,
) -> Trace {
    let mut run = Run::new(role, auto, echo);
    let mut progress_rng = SplitMix64::new(progress_seed);
    for (step, kind) in schedule {
        run.exec(label, step, *kind, &mut progress_rng);
    }
    run.finish(label)
}

/// `execute` under `catch_unwind` so a driver panic fails the case with its
/// seed label (the no-panic oracle, attributably).
fn execute_checked(
    label: &str,
    schedule: &[(Step, ProgressKind)],
    role: Role,
    auto: AutoResponsePolicy,
    echo: CloseEchoPolicy,
    progress_seed: u64,
) -> Trace {
    catch_unwind(AssertUnwindSafe(|| {
        execute(label, schedule, role, auto, echo, progress_seed)
    }))
    .unwrap_or_else(|_| panic!("{label}: the owner-driver run panicked"))
}

fn draw_role(rng: &mut SplitMix64) -> Role {
    if rng.chance(2) {
        Role::Client
    } else {
        Role::Server
    }
}

fn draw_policies(rng: &mut SplitMix64) -> (AutoResponsePolicy, CloseEchoPolicy) {
    let auto = if rng.chance(2) {
        AutoResponsePolicy::PongInboundPing
    } else {
        AutoResponsePolicy::Disabled
    };
    let echo = if rng.chance(2) {
        CloseEchoPolicy::WebSocketImplComposition
    } else {
        CloseEchoPolicy::CoreDraftEcho
    };
    (auto, echo)
}

// ===========================================================================
// TARGET: owner-driver-command-byte-schedules. Entrypoints are prefixed
// `owner_driver_` so the manifest's replay command selects exactly this
// target's campaign.
// ===========================================================================

/// The main campaign: drawn command/byte/EOF/write-progress/shutdown
/// schedules against a real `ConnectionDriver`, each run twice for the
/// determinism oracle.
#[test]
fn owner_driver_schedule_soup_no_panic_deterministic() {
    let mut rng = SplitMix64::new(0xd21e_0001);
    let mut reached = Reached::default();
    for case in 0..4_000u32 {
        let role = draw_role(&mut rng);
        let (auto, echo) = draw_policies(&mut rng);
        let schedule = draw_schedule(&mut rng, role);
        let label = format!("owner_driver schedule case {case}");
        let seed = 0x9403_0000 + u64::from(case);
        let first = execute_checked(&label, &schedule, role, auto, echo, seed);
        let second = execute_checked(&label, &schedule, role, auto, echo, seed);
        assert_eq!(
            first, second,
            "{label}: determinism (identical full owner trace)"
        );
        assert!(
            first.terminals <= 1,
            "{label}: the terminal must be delivered at most once"
        );
        reached.wire += usize::from(!first.wire.is_empty());
        reached.terminals += first.terminals;
        reached.failures += usize::from(first.failures > 0);
        reached.events += usize::from(!first.events.is_empty());
        reached.dropped += usize::from(!first.dropped.is_empty());
    }
    // Coverage floors. A campaign whose every case dies on its first inbound
    // frame runs 4,000 times and exercises nothing; these floors are what
    // stops that degeneration from passing silently.
    //
    // The campaign is fully deterministic (fixed seed, fixed generator), so
    // these are exact reproducible observations, not estimates. Measured on
    // the landed generator: wire 1352, terminals 151, failures 3363,
    // events 3347, dropped 517. The floors sit below each with margin. A
    // deliberate generator change that legitimately moves them is expected
    // to move these numbers WITH a recorded reason, not to delete them.
    reached.assert_floors("owner_driver schedule soup");
}

/// How much of the driver's behavior a campaign actually reached.
#[derive(Debug, Default)]
struct Reached {
    wire: usize,
    terminals: usize,
    failures: usize,
    events: usize,
    dropped: usize,
}

impl Reached {
    fn assert_floors(&self, campaign: &str) {
        assert!(
            self.wire >= 1_000,
            "{campaign}: only {} cases put a byte on the wire",
            self.wire
        );
        assert!(
            self.terminals >= 100,
            "{campaign}: only {} cases reached the terminal",
            self.terminals
        );
        assert!(
            self.failures >= 2_000,
            "{campaign}: only {} cases surfaced a fatal",
            self.failures
        );
        assert!(
            self.events >= 2_500,
            "{campaign}: only {} cases drained a semantic event",
            self.events
        );
        assert!(
            self.dropped >= 350,
            "{campaign}: only {} cases surfaced a dropped-write report",
            self.dropped
        );
    }
}

/// Schedules that ALWAYS end the transport, so the shutdown/EOF accounting
/// oracles are reached on every case rather than occasionally. The
/// exhaustive exploration reaches shutdown only under
/// `AutoResponsePolicy::Disabled`; this family draws both policies.
#[test]
fn owner_driver_transport_termination_accounting() {
    let mut rng = SplitMix64::new(0xd21e_0002);
    let mut with_reports = 0usize;
    for case in 0..3_000u32 {
        let role = draw_role(&mut rng);
        let (auto, echo) = draw_policies(&mut rng);
        let mut schedule = draw_schedule(&mut rng, role);
        // Guarantee committed but undrained wire output before the end.
        schedule.push((
            Step::Enqueue {
                producer: 0,
                command: draw_command(&mut rng),
            },
            ProgressKind::None,
        ));
        schedule.push((Step::Wake, ProgressKind::None));
        if rng.chance(2) {
            schedule.push((Step::WriteProgress(0), ProgressKind::One));
        }
        if rng.chance(2) {
            schedule.push((Step::TransportEof, ProgressKind::None));
        }
        schedule.push((Step::Shutdown, ProgressKind::None));
        let label = format!("owner_driver termination case {case}");
        let seed = 0x9404_0000 + u64::from(case);
        let trace = execute_checked(&label, &schedule, role, auto, echo, seed);
        let replay = execute_checked(&label, &schedule, role, auto, echo, seed);
        assert_eq!(trace, replay, "{label}: determinism");
        if !trace.dropped.is_empty() {
            with_reports += 1;
        }
    }
    assert!(
        with_reports >= 100,
        "a shutdown-accounting campaign that never reaches a dropped-write report \
         proves nothing; reached {with_reports}"
    );
}

/// Backpressure at the bounded producer seam: a command queue of capacity 8
/// with schedules that enqueue far more than that. Every refusal must be
/// the typed bounded refusal, and no accepted command may be lost.
#[test]
fn owner_driver_producer_backpressure_is_typed() {
    let mut rng = SplitMix64::new(0xd21e_0003);
    let mut refusals = 0usize;
    for case in 0..2_000u32 {
        let role = draw_role(&mut rng);
        let (auto, echo) = draw_policies(&mut rng);
        let burst = 8 + rng.below(16) as usize;
        let mut schedule: Vec<(Step, ProgressKind)> = (0..burst)
            .map(|index| {
                (
                    Step::Enqueue {
                        producer: (index & 1) as u8,
                        command: draw_command(&mut rng),
                    },
                    ProgressKind::None,
                )
            })
            .collect();
        for _ in 0..rng.below(6) {
            schedule.push((Step::Wake, ProgressKind::None));
            schedule.push((Step::WriteProgress(0), ProgressKind::Whole));
        }
        let label = format!("owner_driver backpressure case {case}");
        let seed = 0x9405_0000 + u64::from(case);
        let trace = execute_checked(&label, &schedule, role, auto, echo, seed);
        let replay = execute_checked(&label, &schedule, role, auto, echo, seed);
        assert_eq!(trace, replay, "{label}: determinism");
        refusals += trace.refused_enqueues;
        // Every command that was ACCEPTED by the bounded channel must reach
        // a disposition once the owner drains, and none may be invented.
        let accepted = burst - trace.refused_enqueues;
        assert!(
            trace.dispositions.len() <= accepted,
            "{label}: the owner disposed {} commands but only {accepted} were accepted",
            trace.dispositions.len()
        );
        if !trace.halted {
            assert_eq!(
                trace.dispositions.len(),
                accepted,
                "{label}: a quiescent owner must dispose every accepted command"
            );
        }
    }
    assert!(
        refusals >= 100,
        "a backpressure campaign that never fills the bounded channel proves nothing; \
         reached {refusals} refusals"
    );
}

/// The strong form of the invalid-write-progress property, checked where it
/// is actually true: on a QUIESCENT owner (nothing queued, one write
/// offered), a refused progress must move literally nothing -- not the
/// lifecycle state, not one protocol counter, not one byte of the offered
/// suffix.
///
/// This is the deterministic companion to the campaign's weaker per-case
/// check. Keeping the two apart is the point: a poll is an owner turn, so
/// the campaign cannot demand total inertness without becoming an oracle
/// that fails on correct behavior.
#[test]
fn owner_driver_invalid_write_progress_on_a_quiescent_owner_moves_nothing() {
    let (sender, mut driver) = connection_driver_in_state_with_policies(
        config(),
        Role::Server,
        InitialState::Open,
        AutoResponsePolicy::Disabled,
        CloseEchoPolicy::CoreDraftEcho,
    );
    sender
        .try_send(LocalCommand::SendText {
            text: "quiescent".to_owned(),
        })
        .expect("bounded enqueue within capacity");

    // Poll until the write is offered, then keep polling until the owner has
    // nothing left but that offer.
    let mut offered = None;
    for _ in 0..DRAIN_WORK_BOUND {
        let result = driver.poll(DriverInput::Wake);
        match result.output {
            DriverOutput::Write(suffix) => {
                offered = Some(suffix.to_vec());
                break;
            }
            DriverOutput::Idle => panic!("the owner went idle without offering the write"),
            _ => {}
        }
    }
    let offered = offered.expect("the committed text frame must be offered");
    assert!(!offered.is_empty());

    // Take one byte, so the refusal is measured against a partly drained
    // front write rather than a fresh one.
    assert_eq!(
        driver.poll(DriverInput::WriteProgress { bytes: 1 }).input,
        InputDisposition::Consumed { bytes: 0 }
    );
    let remaining = offered.len() - 1;

    let state_before = driver.state();
    let counts_before = driver.counts();
    for overrun in [remaining + 1, remaining + 7, usize::MAX] {
        let result = driver.poll(DriverInput::WriteProgress { bytes: overrun });
        assert_eq!(
            result.input,
            InputDisposition::Rejected(DriverInputError::InvalidWriteProgress {
                attempted: overrun,
                remaining,
            }),
            "an overrun of {overrun} against {remaining} offered bytes must be refused"
        );
        assert_eq!(
            driver.state(),
            state_before,
            "a refused write progress moved the lifecycle state of a quiescent owner"
        );
        assert_eq!(
            driver.counts(),
            counts_before,
            "a refused write progress moved a protocol counter of a quiescent owner"
        );
    }

    // The offer must still be exactly the undrained tail: a refusal may not
    // consume, re-offer, or discard any of it.
    match driver.poll(DriverInput::Wake).output {
        DriverOutput::Write(suffix) => assert_eq!(
            suffix,
            &offered[1..],
            "the refusals disturbed the undrained tail of the offered write"
        ),
        other => panic!("the undrained write must still be offered, got {other:?}"),
    }
}
